### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by CodeTazMan** [pawanaichra/stock-movement-prediction-using-hmm-in-python#6]
Followed instructions in README file and now when enter symbol in text box -
 http://localhost:5000/predict?stock=sndl 

Results in
  500 Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

what is the file location of Flask?   wonder if turn on debug in Flask if it will help to locate reason for error

**Comment by andykov** [comment]
i have the same error

**Comment by CodeTazMan** [comment]
Closed Issue

**Comment by andykov** [comment]
@CodeTazMan  how did you fix the error?
